### ISSUE TITLE
Maintenance 

### ISSUE THREAD

**Issue by jswolf19** [adrianoc/cecil-linqpad-driver#1]
@adrianoc I'm looking into modifying this to work with Linqpad 6, among other things.

I notice you haven't made any changes in about 4 years, but that might be that there's not much to change. If you are interested in maintaining this, I would be more than happy to send my changes as pull requests. Otherwise, I'll just do the edits on my fork.

**Comment by adrianoc** [comment]
@jswolf19 thanks for reaching out.

please, open pull requests and I'll check them.

**Comment by adrianoc** [comment]
merged https://github.com/adrianoc/cecil-linqpad-driver/pull/2

**Comment by jswolf19** [comment]
Thanks. Once I get around to making other changes, I'll make PRs for them as well.
